### PR TITLE
empty booleans should be considered false

### PR DESCRIPTION
**Pull request by markbates**

### CODE REVIEW

**Comment by markbates** [comment]
@dashaus I'm wondering if any value, or lack of values, that isn't `"true", "on", "1"` should be `false`. thoughts?

**Comment by markbates** [comment]
Also, I would it if you would trust me with commit access to this project. It is now shipping with https://github.com/gobuffalo/buffalo so it would be great to be able to make quicker commits. I would understand if don't want to. Just asking.

**Comment by dashaus** [comment]
I have never given access to anyone. How I do it?

**Comment by dashaus** [comment]
I forgot, thanks for the PR!

**Comment by markbates** [comment]
Just go to Settings (for the project) > Collaborators & Teams > Add collaborator. :)

**Comment by dashaus** [comment]
Done!

**Comment by markbates** [comment]
Awesome! Thanks so much!

**Comment by markbates** [comment]
What do you think about saying that any value that isn't a "true" value for a boolean be "false"?

**Comment by dashaus** [comment]
I see it right!

**Pull request merged**
